version: '3'
services:
  app:
    container_name: "slack-app"
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        STAGE: dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true