name: deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: yarn install --frozen-lockfile

      - name: gcr-push
        run: gcloud builds submit --project=${{ secrets.PROJECT }} --config cloudbuild.yml

      - name: gcr-deploy
        run: make gcr-push STAGE=${{ secrets.STAGE }} SERVICE_NAME=${{ secrets.SERVICE_NAME }} PROJECT=${{ secrets.PROJECT }}

      - name: gcr-deploy
      - run: open https://console.cloud.google.com/run?hl=ja&project=${{ secrets.PROJECT }}
